# Generated by Django 5.2.4 on 2025-07-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('affected', models.TextField()),
                ('sector_impacts', models.JSONField()),
                ('most_sector', models.CharField(max_length=100)),
                ('most_text', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('uploaded_from', models.CharField(choices=[('file', 'File'), ('url', 'URL')], default='file', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='URLExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
