# Generated by Django 5.2.4 on 2025-07-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlextractionjob',
            name='status',
        ),
        migrations.RemoveField(
            model_name='urlextractionjob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='urlextractionjob',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='urlextractionjob',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
