# Generated by Django 5.2.4 on 2025-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_remove_urlextractionjob_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlextractionjob',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='urlextractionjob',
            name='is_paused',
        ),
        migrations.AddField(
            model_name='urlextractionjob',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
