# Generated by Django 5.2.4 on 2025-07-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_remove_urlextractionjob_is_complete_and_more'),
    ]

    operations = [
    ]
