# Generated by Django 5.2.4 on 2025-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20250710_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlextractionjob',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='in_progress', max_length=1000),
        ),
        migrations.AlterField(
            model_name='urlextractionjob',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
