# Generated by Django 5.2.4 on 2025-07-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_alter_urlextractionjob_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_links', to='policy.urlextractionjob')),
            ],
        ),
    ]
