# Generated by Django 5.2.4 on 2025-07-11 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_pdflink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdflink',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.urlextractionjob'),
        ),
        migrations.AlterField(
            model_name='pdflink',
            name='link',
            field=models.URLField(),
        ),
    ]
