# Generated by Django 5.2.4 on 2025-07-15 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_alter_pdflink_job_alter_pdflink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdflink',
            name='link_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML')], default='html', max_length=10),
        ),
        migrations.AddField(
            model_name='pdflink',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdflink',
            name='link',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='urlextractionjob',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='in_progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlextractionjob',
            name='url',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterUniqueTogether(
            name='pdflink',
            unique_together={('job', 'link')},
        ),
    ]
