# Generated by Django 5.2.4 on 2025-07-15 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0008_pdflink_link_type_pdflink_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdflink',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
