# Generated by Django 5.2.4 on 2025-07-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_alter_pdflink_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdflink',
            name='link',
            field=models.URLField(max_length=6048),
        ),
    ]
