# Generated by Django 5.2.4 on 2025-07-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0010_alter_pdflink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdflink',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_text', to='policy.pdflink')),
            ],
        ),
    ]
